import { defineCategory, defineChapter, outline, q } from '@/lib/curriculum/authoring';

/** Backend Intermediate — 5 chapters, 58 lessons. */

const desainApi = defineChapter({
  slug: 'desain-api',
  number: 1,
  title: 'Desain API yang Baik',
  summary:
    'Kontrak API yang bisa dipakai klien lain tanpa bertanya, dan bisa berkembang tanpa merusak.',
  objectives: [
    'Merancang URL, status code, dan bentuk error yang konsisten',
    'Memilih antara paginasi offset dan cursor dengan alasan',
    'Menjaga kompatibilitas mundur saat API berubah',
  ],
  prerequisites: [{ category: 'backend-basic', chapter: 'nodejs-express-basic' }],
  stackVersions: ['RFC 9457', 'OpenAPI 3.1'],
  reviewedAt: '2026-08-01',
  lessons: [
    outline(
      'penamaan-resource',
      'Penamaan Resource & Struktur URL',
      10,
      'URL yang bisa ditebak tanpa membaca dokumentasi.',
      'Kata benda jamak, hierarki, dan batas kedalaman',
      'Kapan sebuah aksi memang tidak muat dalam bentuk resource',
    ),
    outline(
      'status-code-tepat',
      'Memilih Status Code yang Tepat',
      11,
      'Kode yang menyampaikan arti, bukan sekadar 200 dan 500.',
      '400 vs 401 vs 403 vs 404 vs 409 vs 422',
      'Kenapa "200 dengan field error" menyulitkan klien',
    ),
    outline(
      'bentuk-error',
      'Bentuk Error Seragam (RFC 9457)',
      11,
      'Satu bentuk error untuk seluruh API.',
      '`type`, `title`, `status`, `detail`, `instance`',
      'Detail teknis tetap di log server, bukan di respons',
    ),
    outline(
      'paginasi',
      'Paginasi: offset vs cursor',
      12,
      'Dua pendekatan dan konsekuensinya pada data yang berubah.',
      'Offset yang sederhana tapi melewatkan data saat ada penyisipan',
      'Cursor yang stabil dan cocok untuk data besar',
    ),
    outline(
      'filter-sort',
      'Filtering, Sorting & Sparse Fieldset',
      11,
      'Membiarkan klien meminta persis yang dibutuhkannya.',
      'Sintaks filter yang konsisten',
      'Sorting dengan allow-list kolom — bukan interpolasi langsung',
    ),
    outline(
      'versioning',
      'Versioning & Kompatibilitas Mundur',
      12,
      'Mengubah API tanpa merusak klien yang sudah ada.',
      'Versi di path, header, atau tidak sama sekali',
      'Perubahan yang aman vs yang merusak',
    ),
    outline(
      'idempotency',
      'Idempotency & `Idempotency-Key`',
      11,
      'Menahan efek permintaan ganda akibat retry atau klik dobel.',
      'Method yang idempoten secara alami',
      'Idempotency key untuk `POST` yang tidak boleh terjadi dua kali',
    ),
    outline(
      'caching-http',
      'Caching HTTP: `ETag` & `Cache-Control`',
      11,
      'Menghemat bandwidth dan waktu tanpa menyajikan data basi.',
      '`ETag` dan permintaan bersyarat',
      '`Cache-Control` untuk respons publik dan privat',
    ),
    outline(
      'operasi-panjang',
      'Operasi Panjang: `202 Accepted` + job id',
      10,
      'Pekerjaan yang tidak muat dalam satu permintaan.',
      'Mengembalikan job id dan endpoint status',
      'Kenapa menahan koneksi selama satu menit adalah kesalahan',
    ),
    outline(
      'openapi',
      'Dokumentasi API dengan OpenAPI',
      11,
      'Kontrak yang bisa dibaca manusia dan mesin.',
      'Menulis spesifikasi dan menghasilkan tipe klien',
      'Menjaga dokumentasi tetap sinkron dengan kode',
    ),
    outline(
      'praktik-audit-api',
      'Praktik: Audit API CRUD-mu sendiri',
      13,
      'Menilai API dari bab sebelumnya terhadap sepuluh poin di atas.',
      'Mencatat pelanggaran dan memperbaikinya satu per satu',
      'Menulis spesifikasi OpenAPI untuk hasil akhirnya',
    ),
  ],
  quiz: [
    q(
      'bi1-q1',
      'Kapan paginasi berbasis cursor lebih tepat daripada offset?',
      [
        'Selalu',
        'Saat data sering berubah atau jumlahnya sangat besar, karena offset bisa melewatkan atau menggandakan baris',
        'Saat data statis',
        'Saat memakai GraphQL',
      ],
      1,
      'Kalau baris baru disisipkan di antara dua permintaan, `OFFSET 20` menunjuk baris yang berbeda dari sebelumnya. Cursor menunjuk posisi berdasarkan nilai, bukan hitungan, sehingga stabil.',
    ),
    q(
      'bi1-q2',
      'Apa fungsi `Idempotency-Key`?',
      [
        'Mengenkripsi permintaan',
        'Memastikan permintaan yang sama diulang tidak menghasilkan efek ganda, misalnya pembayaran dobel',
        'Mempercepat respons',
        'Menggantikan autentikasi',
      ],
      1,
      'Klien mengirim kunci unik per operasi. Kalau permintaan dengan kunci yang sama datang lagi — karena timeout lalu retry — server mengembalikan hasil yang pertama alih-alih memproses ulang.',
    ),
    q(
      'bi1-q3',
      'Mana yang termasuk perubahan yang merusak (breaking change)?',
      [
        'Menambah field opsional di respons',
        'Menghapus field yang sudah ada di respons',
        'Menambah endpoint baru',
        'Memperbaiki typo di dokumentasi',
      ],
      1,
      'Klien yang membaca field itu akan rusak. Menambah field umumnya aman; menghapus atau mengubah tipe tidak. Kalau harus, tempuh jalur deprecate dulu, hapus di versi berikutnya.',
    ),
  ],
  practice: {
    id: 'backend-intermediate/desain-api',
    title: 'Praktik bab ini',
    items: [
      'Audit API-mu terhadap sepuluh poin bab ini dan catat pelanggarannya',
      'Ubah bentuk error menjadi satu format seragam',
      'Ganti paginasi offset menjadi cursor pada satu endpoint',
      'Tulis spesifikasi OpenAPI untuk satu resource',
    ],
  },
});

const expressLanjut = defineChapter({
  slug: 'express-intermediate',
  number: 2,
  title: 'ExpressJS Intermediate',
  summary:
    'Dari API contoh menjadi API produksi: ORM, transaksi, queue, cache, test, dan observability.',
  objectives: [
    'Memakai ORM dengan transaksi dan relasi yang benar',
    'Memindahkan pekerjaan berat ke queue',
    'Menulis test integrasi yang menjalankan jalur kode sungguhan',
  ],
  prerequisites: [{ category: 'backend-basic', chapter: 'nodejs-express-basic' }],
  stackVersions: ['Express 5', 'Prisma 6', 'BullMQ 5', 'Vitest 4'],
  reviewedAt: '2026-08-01',
  lessons: [
    outline(
      'arsitektur-berlapis',
      'Arsitektur Berlapis & Dependency Injection Sederhana',
      11,
      'Struktur yang tetap terbaca setelah setahun.',
      'Arah ketergantungan antar lapisan',
      'Injeksi dependensi tanpa framework',
    ),
    outline(
      'prisma',
      'ORM: Prisma',
      13,
      'Skema, migrasi, dan klien bertipe.',
      '`schema.prisma`, `migrate dev`, dan klien yang dihasilkan',
      'Kapan raw query masih lebih tepat',
    ),
    outline(
      'relasi-query-kompleks',
      'Relasi & Query Kompleks di ORM',
      12,
      'Melampaui `findMany` sederhana.',
      'Relasi bersarang dan pemilihan field',
      'Menghindari N+1 dan query yang menarik terlalu banyak data',
    ),
    outline(
      'transaksi-orm',
      'Transaksi Database',
      11,
      'Beberapa penulisan yang harus utuh.',
      'Transaksi interaktif dan batch',
      'Jangan pernah menahan transaksi melintasi panggilan jaringan',
    ),
    outline(
      'auth-produksi',
      'Autentikasi Produksi: JWT + refresh + pencabutan',
      13,
      'Dari contoh menjadi implementasi yang bisa dipercaya.',
      'Rotasi refresh token dan deteksi pemakaian ulang',
      'Pencabutan saat logout, ganti password, dan perubahan izin',
    ),
    outline(
      'middleware-keamanan',
      'Middleware Keamanan: helmet, CORS, rate limit',
      12,
      'Lapisan pertahanan standar yang wajib ada.',
      'Header keamanan dan CORS dengan allow-list origin yang persis',
      'Rate limit per endpoint, paling ketat di endpoint sensitif',
    ),
    outline(
      'upload-aman',
      'Upload Berkas yang Aman',
      12,
      'Salah satu jalur masuk paling sering dieksploitasi.',
      'Allow-list ekstensi dan verifikasi magic byte, bukan `Content-Type`',
      'Nama berkas acak dari server, disimpan di luar webroot',
    ),
    outline(
      'queue-bullmq',
      'Background Job & Queue dengan BullMQ',
      13,
      'Memindahkan pekerjaan lambat keluar dari jalur permintaan.',
      'Producer, worker, dan retry dengan backoff',
      'Handler harus idempoten — pengiriman at-least-once',
    ),
    outline(
      'cache-redis',
      'Caching dengan Redis',
      12,
      'Menghemat pekerjaan yang berulang.',
      'Pola cache-aside dan penentuan TTL',
      'Invalidasi: bagian tersulit, dan cara menghindarinya',
    ),
    outline(
      'testing-express',
      'Testing: Vitest + Supertest',
      13,
      'Test yang benar-benar menjalankan endpoint.',
      'Unit untuk logika, integrasi lewat HTTP',
      'Menguji jalur gagal dan otorisasi negatif',
    ),
    outline(
      'socketio',
      'Realtime dengan Socket.IO',
      11,
      'Komunikasi dua arah di atas Express.',
      'Room, namespace, dan penyiaran',
      'Autentikasi koneksi socket',
    ),
    outline(
      'observability',
      'Observability: logging, request id, health check',
      12,
      'Membuat masalah bisa ditelusuri setelah terjadi.',
      'Correlation id yang mengalir ke seluruh log satu permintaan',
      'Health check dan metrik yang benar-benar dibaca',
    ),
    outline(
      'typescript-express',
      'TypeScript di Express',
      11,
      'Tipe yang menjaga request dan response tetap benar.',
      'Mengetik body, param, dan query hasil validasi',
      'Memperluas tipe `Request` dengan aman',
    ),
    outline(
      'praktik-api-blog-express',
      'Praktik: API blog lengkap beserta testnya',
      15,
      'Menggabungkan seluruh bab menjadi satu aplikasi.',
      'Auth, CRUD, upload, queue, dan cache dalam satu API',
      'Test integrasi untuk jalur sukses dan jalur gagal',
    ),
  ],
  quiz: [
    q(
      'bi2-q1',
      'Kenapa handler job di queue harus idempoten?',
      [
        'Supaya lebih cepat',
        'Karena antrean umumnya menjamin at-least-once delivery, sehingga satu job bisa dijalankan lebih dari sekali',
        'Karena Redis membutuhkannya',
        'Karena job tidak boleh gagal',
      ],
      1,
      'Worker yang mati setelah bekerja tapi sebelum menandai selesai akan membuat job diambil lagi. Kalau handler mengirim email atau memotong saldo, efeknya terjadi dua kali kecuali ia idempoten.',
    ),
    q(
      'bi2-q2',
      'Kenapa `Content-Type` dari klien tidak boleh dipercaya saat upload berkas?',
      [
        'Karena sering kosong',
        'Karena sepenuhnya dikendalikan pengirim; berkas berbahaya bisa mengaku sebagai gambar',
        'Karena browser tidak mengirimnya',
        'Karena melanggar standar HTTP',
      ],
      1,
      'Verifikasi isi berkasnya (magic byte), simpan dengan nama yang dihasilkan server, dan letakkan di lokasi yang tidak mungkin dieksekusi.',
    ),
    q(
      'bi2-q3',
      'Apa yang tidak boleh dilakukan di dalam sebuah transaksi database?',
      [
        'Menulis ke dua tabel',
        'Memanggil layanan eksternal lewat jaringan dan menunggu responsnya',
        'Membaca data',
        'Memakai `ROLLBACK`',
      ],
      1,
      'Transaksi menahan kunci. Menahannya selama panggilan HTTP yang bisa memakan detik atau timeout akan memblokir penulisan lain dan memicu deadlock.',
    ),
  ],
  practice: {
    id: 'backend-intermediate/express-intermediate',
    title: 'Praktik bab ini',
    items: [
      'Pindahkan satu operasi lambat ke queue dengan retry dan dead letter',
      'Tulis test integrasi untuk satu endpoint, termasuk kasus tanpa izin',
      'Pasang correlation id yang muncul di seluruh log satu permintaan',
      'Amankan endpoint upload dengan verifikasi isi berkas',
    ],
  },
});

const laravelLanjut = defineChapter({
  slug: 'laravel-intermediate',
  number: 3,
  title: 'Laravel Intermediate',
  summary:
    'Fitur Laravel yang membuatnya menang di aplikasi nyata: queue, policy, event, dan testing.',
  objectives: [
    'Memisahkan logika bisnis dari controller dengan service layer',
    'Mengamankan endpoint dengan Sanctum dan Policy',
    'Menulis test Pest untuk fitur dan unit',
  ],
  prerequisites: [{ category: 'backend-basic', chapter: 'php-laravel-basic' }],
  stackVersions: ['Laravel 12', 'PHP 8.3+', 'Pest 3'],
  reviewedAt: '2026-08-01',
  lessons: [
    outline(
      'service-repository',
      'Service Layer & Repository di Laravel',
      11,
      'Menjaga controller tetap tipis saat aplikasi tumbuh.',
      'Kapan service layer benar-benar membantu',
      'Repository: berguna atau lapisan tambahan tanpa manfaat?',
    ),
    outline(
      'eloquent-lanjutan',
      'Eloquent Lanjutan: scope, accessor, casts',
      12,
      'Membuat model lebih ekspresif tanpa membuatnya gemuk.',
      'Query scope untuk filter yang berulang',
      'Accessor, mutator, dan custom cast',
    ),
    outline(
      'n-plus-one',
      'Masalah N+1 & Eager Loading',
      11,
      'Penyebab lambat paling umum di aplikasi Laravel.',
      'Mendeteksinya dengan Telescope atau query log',
      '`with`, `load`, dan `preventLazyLoading`',
    ),
    outline(
      'sanctum',
      'API Auth dengan Sanctum',
      12,
      'Autentikasi untuk SPA dan untuk token API.',
      'Mode SPA berbasis cookie vs personal access token',
      'Trusted origins dan konfigurasi yang sering salah',
    ),
    outline(
      'policy-gate',
      'Policy & Gate',
      12,
      'Otorisasi yang terpusat dan bisa diuji.',
      'Policy per model dan pemetaan aksinya',
      'Otorisasi di lapisan data, bukan hanya di Blade',
    ),
    outline(
      'queue-horizon',
      'Queue & Job, Horizon',
      12,
      'Pekerjaan latar di Laravel.',
      'Driver database vs Redis, retry, dan failed jobs',
      'Horizon untuk memantau antrean',
    ),
    outline(
      'event-listener-observer',
      'Event, Listener & Observer',
      11,
      'Memisahkan efek samping dari alur utama.',
      'Kapan event membantu dan kapan ia menyembunyikan alur',
      'Observer pada model dan risikonya',
    ),
    outline(
      'task-scheduling',
      'Task Scheduling',
      9,
      'Pekerjaan berkala tanpa cron yang tersebar.',
      'Definisi jadwal di kode',
      'Mencegah tumpang tindih dan menangani kegagalan',
    ),
    outline(
      'caching-optimasi',
      'Caching & Optimasi Query',
      12,
      'Mempercepat tanpa menebak.',
      'Cache query dan cache fragment',
      'Mengukur dulu dengan Telescope atau Debugbar',
    ),
    outline(
      'notification-mail',
      'Notification & Mail',
      10,
      'Mengirim pemberitahuan lewat beberapa kanal.',
      'Notification dan channel',
      'Mengirim lewat queue supaya tidak menahan permintaan',
    ),
    outline(
      'testing-pest',
      'Testing dengan Pest',
      13,
      'Test yang cepat ditulis dan cepat dibaca.',
      'Feature test lewat HTTP dan unit test untuk logika',
      'Factory, database transaction, dan test otorisasi negatif',
    ),
    outline(
      'file-storage',
      'File Storage & S3-compatible',
      10,
      'Menyimpan berkas di luar server aplikasi.',
      'Disk, driver, dan URL bertanda tangan',
      'Kenapa berkas unggahan tidak boleh berada di webroot',
    ),
    outline(
      'praktik-api-blog-laravel',
      'Praktik: API blog lengkap beserta testnya',
      15,
      'Membangun aplikasi yang setara dengan versi Express.',
      'Auth Sanctum, Policy, queue, dan storage',
      'Membandingkan kecepatan pengembangan kedua stack',
    ),
  ],
  quiz: [
    q(
      'bi3-q1',
      'Apa fungsi Policy di Laravel?',
      [
        'Memvalidasi input',
        'Memusatkan aturan otorisasi per model sehingga bisa dipanggil dari controller, route, maupun view',
        'Mengatur routing',
        'Mengelola migrasi',
      ],
      1,
      'Tanpa Policy, aturan "hanya pemilik yang boleh mengubah" tersebar di banyak controller dan mudah terlewat di salah satunya.',
    ),
    q(
      'bi3-q2',
      'Kenapa mengirim email sebaiknya lewat queue?',
      [
        'Karena lebih murah',
        'Karena pengiriman email bisa memakan detik dan menahan respons permintaan pengguna',
        'Karena Laravel mewajibkannya',
        'Karena email tidak bisa dikirim sinkron',
      ],
      1,
      'Selain lambat, layanan email bisa gagal sementara. Di queue, kegagalan bisa diulang dengan backoff tanpa membuat pengguna melihat error.',
    ),
  ],
  practice: {
    id: 'backend-intermediate/laravel-intermediate',
    title: 'Praktik bab ini',
    items: [
      'Tulis Policy untuk satu model dan uji jalur ditolaknya',
      'Pindahkan pengiriman notifikasi ke queue',
      'Temukan dan perbaiki satu masalah N+1 dengan bukti jumlah query',
      'Tulis feature test Pest untuk seluruh CRUD satu resource',
    ],
  },
});

const menyambung = defineChapter({
  slug: 'menyambung-frontend-backend',
  number: 4,
  title: 'Menyambungkan Frontend & Backend',
  summary: 'Titik temu keduanya — tempat sebagian besar bug integrasi lahir.',
  objectives: [
    'Menjaga tipe frontend tetap sinkron dengan kontrak API',
    'Memilih strategi autentikasi lintas domain yang konsisten',
    'Menangani kegagalan secara end-to-end tanpa membocorkan detail internal',
  ],
  prerequisites: [
    { category: 'backend-intermediate', chapter: 'desain-api' },
    { category: 'frontend-intermediate', chapter: 'state-management' },
  ],
  stackVersions: ['Next.js 16.2', 'OpenAPI 3.1'],
  reviewedAt: '2026-08-01',
  lessons: [
    outline(
      'kontrak-tipe-bersama',
      'Kontrak API & Tipe Bersama',
      12,
      'Satu sumber kebenaran untuk bentuk data.',
      'Menghasilkan tipe TypeScript dari OpenAPI',
      'Kenapa mengetik ulang respons secara manual selalu menyimpang',
    ),
    outline(
      'cors-praktik',
      'CORS dalam Praktik',
      11,
      'Menyelesaikan masalah CORS dengan benar, bukan dengan `*`.',
      'Allow-list origin yang persis, dan jangan pantulkan `Origin`',
      'Kenapa `*` bersama credentials adalah kombinasi terlarang',
    ),
    outline(
      'auth-lintas-domain',
      'Autentikasi Lintas Domain: cookie vs bearer',
      13,
      'Dua pola, dua daftar risiko.',
      'Cookie `SameSite` dan kebutuhan proteksi CSRF',
      'Bearer token dan risiko XSS bila disimpan sembarangan',
    ),
    outline(
      'error-end-to-end',
      'Penanganan Error End-to-End',
      12,
      'Dari exception di server sampai pesan di layar.',
      'Memetakan bentuk error API ke pesan yang bisa ditindaklanjuti',
      'Detail teknis tetap di log, bukan di layar pengguna',
    ),
    outline(
      'optimistic-sinkronisasi',
      'Optimistic Update & Sinkronisasi Cache',
      12,
      'Menjaga tampilan tetap responsif tanpa berbohong.',
      'Memperbarui cache lebih dulu dan membatalkannya saat gagal',
      'Invalidasi setelah mutasi',
    ),
    outline(
      'upload-frontend',
      'Upload Berkas dari Frontend',
      11,
      'Alur unggah yang lengkap.',
      'Unggah langsung ke storage dengan URL bertanda tangan',
      'Progres, pembatalan, dan validasi ganda',
    ),
    outline(
      'realtime-frontend',
      'Realtime di Sisi Frontend',
      11,
      'Menerima pembaruan tanpa menekan tombol muat ulang.',
      'Menyambungkan WebSocket ke state aplikasi',
      'Menyambung ulang dan menyelesaikan konflik data',
    ),
    outline(
      'praktik-sambungkan',
      'Praktik: Sambungkan Next.js ke API Express dan Laravel',
      14,
      'Satu frontend, dua backend, kontrak yang sama.',
      'Menyusun klien API bertipe',
      'Membuktikan kedua backend bisa ditukar tanpa mengubah frontend',
    ),
  ],
  quiz: [
    q(
      'bi4-q1',
      'Kenapa `Access-Control-Allow-Origin: *` tidak boleh dipakai bersama `Allow-Credentials: true`?',
      [
        'Karena melanggar sintaks HTTP',
        'Karena artinya situs mana pun bisa mengirim permintaan dengan cookie pengguna dan membaca hasilnya',
        'Karena browser mengabaikannya',
        'Karena membuat permintaan lambat',
      ],
      1,
      'Browser memang menolak kombinasi itu, dan alasannya penting: ia setara dengan mengizinkan setiap situs bertindak atas nama pengguna yang sedang login.',
    ),
    q(
      'bi4-q2',
      'Apa cara terbaik menjaga tipe frontend tetap sesuai respons API?',
      [
        'Menulis ulang tipenya secara manual dan rajin memperbaruinya',
        'Menghasilkan tipe dari spesifikasi API sehingga perubahan kontrak langsung menjadi error kompilasi',
        'Memakai `any`',
        'Mengandalkan test end-to-end saja',
      ],
      1,
      'Tipe yang ditulis manual akan menyimpang, dan penyimpangannya baru ketahuan di runtime. Tipe hasil generate mengubah perubahan kontrak menjadi error saat build.',
    ),
  ],
  practice: {
    id: 'backend-intermediate/menyambung-frontend-backend',
    title: 'Praktik bab ini',
    items: [
      'Hasilkan tipe TypeScript dari spesifikasi OpenAPI API-mu',
      'Konfigurasikan CORS dengan allow-list origin yang persis',
      'Tangani satu kegagalan API dari server sampai pesan di layar',
      'Terapkan optimistic update pada satu mutasi lalu uji kasus gagalnya',
    ],
  },
});

const keamanan = defineChapter({
  slug: 'keamanan-backend',
  number: 5,
  title: 'Keamanan Backend (OWASP Top 10 dalam Praktik)',
  summary:
    'Sepuluh kategori kerentanan paling umum, dengan contoh kode yang salah dan perbaikannya.',
  objectives: [
    'Mengenali kerentanan di kode sendiri sebelum orang lain menemukannya',
    'Menerapkan kontrol yang tepat untuk tiap kategori',
    'Menyusun checklist keamanan yang benar-benar dijalankan sebelum rilis',
  ],
  prerequisites: [{ category: 'backend-basic', chapter: 'auth-dasar' }],
  stackVersions: ['OWASP Top 10 (2021)', 'OWASP ASVS 5'],
  reviewedAt: '2026-08-01',
  lessons: [
    outline(
      'broken-access-control',
      'Broken Access Control',
      13,
      'Kategori nomor satu, dan yang paling sering ditemukan.',
      'IDOR, privilege escalation, dan endpoint yang lupa dijaga',
      'Default deny, dan pemeriksaan di lapisan data',
    ),
    outline(
      'cryptographic-failures',
      'Cryptographic Failures & Data Sensitif',
      12,
      'Data yang seharusnya tidak terbaca, ternyata terbaca.',
      'TLS di setiap hop, bukan hanya di tepi publik',
      'Apa yang boleh dan tidak boleh disimpan',
    ),
    outline(
      'injection',
      'Injection: SQL, NoSQL, Command',
      13,
      'Data yang berubah menjadi perintah.',
      'Parameterisasi dan allow-list identifier',
      'Command injection dan kenapa argumen harus berupa array',
    ),
    outline(
      'insecure-design',
      'Insecure Design & Threat Modeling Ringkas',
      11,
      'Kerentanan yang tidak bisa ditambal karena ada di rancangannya.',
      'Threat modeling sederhana: apa yang berharga, siapa penyerangnya',
      'Batas kepercayaan dan tempat memeriksanya',
    ),
    outline(
      'security-misconfiguration',
      'Security Misconfiguration & Header',
      12,
      'Kerentanan yang datang dari pengaturan, bukan kode.',
      'Debug mode di produksi, endpoint admin terbuka',
      'CSP, HSTS, `X-Content-Type-Options`, `Referrer-Policy`',
    ),
    outline(
      'vulnerable-components',
      'Komponen Rentan & Audit Dependency',
      11,
      'Kode orang lain yang berjalan dengan hak aplikasimu.',
      '`npm audit`, `composer audit`, dan lockfile',
      'Menilai kesehatan paket sebelum menambahkannya',
    ),
    outline(
      'auth-failures',
      'Kegagalan Identifikasi & Autentikasi',
      12,
      'Cara masuk yang seharusnya tertutup.',
      'Brute force, credential stuffing, session fixation',
      'MFA untuk akun berhak istimewa',
    ),
    outline(
      'integrity-failures',
      'Integritas Software & Data',
      11,
      'Kode atau data yang diubah di tengah jalan.',
      'Supply chain: paket berbahaya dan typosquatting',
      'Deserialisasi tidak aman',
    ),
    outline(
      'logging-monitoring-failures',
      'Kegagalan Logging & Monitoring',
      11,
      'Serangan yang tidak pernah terdeteksi.',
      'Peristiwa keamanan yang wajib dicatat',
      'Log tanpa alert adalah arsip, bukan deteksi',
    ),
    outline(
      'ssrf',
      'SSRF',
      12,
      'Server yang dipaksa memanggil alamat pilihan penyerang.',
      'Fitur yang rawan: import dari URL, webhook, image proxy',
      'Allow-list tujuan dan pemblokiran rentang IP internal',
    ),
    outline(
      'rahasia-konfigurasi',
      'Rahasia & Konfigurasi',
      12,
      'Kredensial yang bocor lewat jalur yang tidak diduga.',
      'Vault, injeksi saat deploy, dan rotasi',
      'Rahasia yang pernah ter-commit harus dianggap bocor',
    ),
    outline(
      'praktik-checklist-keamanan',
      'Praktik: Checklist keamanan sebelum rilis',
      13,
      'Mengubah bab ini menjadi daftar periksa yang benar-benar dipakai.',
      'Menyusun checklist untuk aplikasimu sendiri',
      'Menjalankannya pada API blog yang sudah kamu buat',
    ),
  ],
  quiz: [
    q(
      'bi5-q1',
      'Kategori OWASP mana yang menempati peringkat pertama?',
      ['Injection', 'Broken Access Control', 'Cryptographic Failures', 'SSRF'],
      1,
      'Sejak daftar 2021, Broken Access Control naik ke peringkat satu. Sebagian besarnya adalah hal sederhana: endpoint yang lupa memeriksa kepemilikan data.',
    ),
    q(
      'bi5-q2',
      'Apa yang membuat SSRF berbahaya?',
      [
        'Ia memperlambat server',
        'Server memanggil alamat pilihan penyerang, termasuk layanan internal dan endpoint metadata cloud yang tidak terjangkau dari luar',
        'Ia merusak database',
        'Ia hanya memengaruhi frontend',
      ],
      1,
      'Server-mu berada di dalam perimeter. Satu fitur "ambil dari URL" tanpa allow-list bisa dipakai membaca `169.254.169.254` dan mengambil kredensial instance.',
    ),
    q(
      'bi5-q3',
      'Apa yang harus dilakukan pada rahasia yang pernah ter-commit ke git?',
      [
        'Cukup hapus commitnya',
        'Rotasi rahasianya, karena riwayat kemungkinan besar sudah ter-clone atau terindeks',
        'Ubah namanya',
        'Tidak perlu apa-apa jika repo privat',
      ],
      1,
      'Menulis ulang riwayat tidak menarik kembali salinan yang sudah tersebar. Satu-satunya tindakan yang benar-benar menutup kebocoran adalah mengganti rahasianya.',
    ),
  ],
  practice: {
    id: 'backend-intermediate/keamanan-backend',
    title: 'Praktik bab ini',
    items: [
      'Cari satu IDOR di API-mu sendiri dan perbaiki',
      'Jalankan audit dependency dan tindak lanjuti temuannya',
      'Pasang header keamanan dan verifikasi dengan `curl -I`',
      'Susun checklist keamanan pra-rilis untuk aplikasimu',
    ],
  },
});

export const backendIntermediate = defineCategory({
  slug: 'backend-intermediate',
  order: 4,
  title: 'Backend Intermediate',
  tagline: 'Dari berjalan menjadi layak dipakai',
  description:
    'Desain kontrak API, fitur produksi di kedua stack, titik temu dengan frontend, dan keamanan yang diperlakukan sebagai bagian dari pekerjaan — bukan tugas terpisah di akhir.',
  chapters: [desainApi, expressLanjut, laravelLanjut, menyambung, keamanan],
});
