import { defineCategory, defineChapter, outline, q } from '@/lib/curriculum/authoring';

/** Deployment — 7 chapters, 38 lessons. The closing category. */

const fondasi = defineChapter({
  slug: 'fondasi-deployment',
  number: 1,
  title: 'Fondasi Deployment',
  summary: 'Konsep yang harus jelas sebelum menyentuh satu pun perintah deploy.',
  objectives: [
    'Membedakan apa yang terjadi saat build dan saat runtime',
    'Menyimpan konfigurasi per environment tanpa membocorkan rahasia',
    'Menjelaskan peran reverse proxy di depan aplikasi',
  ],
  prerequisites: [],
  stackVersions: ['Nginx 1.27', 'Caddy 2'],
  reviewedAt: '2026-08-01',
  lessons: [
    outline(
      'dev-staging-prod',
      'Beda Development, Staging & Production',
      9,
      'Tiga lingkungan dan alasan masing-masing ada.',
      'Apa yang boleh berbeda dan apa yang harus sama',
      'Kenapa "berhasil di laptop saya" bukan bukti',
    ),
    outline(
      'build-vs-runtime',
      'Build vs Runtime',
      10,
      'Dua fase yang sering tertukar, dan akibatnya.',
      'Nilai yang dibekukan saat build vs dibaca saat jalan',
      'Kenapa mengubah env setelah build kadang tidak berpengaruh',
    ),
    outline(
      'env-secret',
      'Environment Variable & Secret Management',
      12,
      'Menaruh rahasia di tempat yang benar.',
      'Vault vs env yang disuntikkan platform saat deploy',
      'Rahasia tidak boleh masuk image, artefak build, bundle klien, atau log CI',
    ),
    outline(
      'domain-dns-tls',
      'Domain, DNS & HTTPS/TLS',
      11,
      'Dari nama domain sampai gembok di address bar.',
      'A record, CNAME, dan propagasi',
      'Sertifikat otomatis, HSTS, dan jangan pernah mematikan verifikasi',
    ),
    outline(
      'reverse-proxy',
      'Reverse Proxy & Load Balancer Sekilas',
      11,
      'Lapisan di depan aplikasi.',
      'Terminasi TLS, kompresi, dan berkas statis',
      'Kenapa aplikasi Node atau PHP-FPM jarang menghadap internet langsung',
    ),
  ],
  quiz: [
    q(
      'dp1-q1',
      'Kenapa mengubah environment variable setelah build kadang tidak berpengaruh?',
      [
        'Karena servernya perlu di-restart saja',
        'Karena sebagian nilai disisipkan ke dalam artefak saat build, sehingga hanya berubah bila di-build ulang',
        'Karena env hanya berlaku di development',
        'Karena namanya salah',
      ],
      1,
      'Variabel yang dipakai di sisi klien dibekukan saat build. Variabel yang dibaca server saat runtime memang cukup di-restart. Membedakan keduanya menghemat berjam-jam kebingungan.',
    ),
  ],
  practice: {
    id: 'deployment/fondasi-deployment',
    title: 'Praktik bab ini',
    items: [
      'Daftar semua variabel yang dibutuhkan aplikasimu dan tandai mana yang publik',
      'Pasang HTTPS pada satu domain uji',
      'Konfigurasikan reverse proxy sederhana di depan aplikasi lokal',
    ],
  },
});

const git = defineChapter({
  slug: 'git-alur-rilis',
  number: 2,
  title: 'Git & Alur Kerja Rilis',
  summary:
    'Kendali versi sebagai jaring pengaman, dan alur kerja yang membuat rilis bisa diprediksi.',
  objectives: [
    'Memakai branch dan pull request dengan disiplin',
    'Menulis pesan commit yang menjelaskan alasan, bukan mengulang diff',
    'Menandai versi rilis secara konsisten',
  ],
  prerequisites: [],
  stackVersions: ['Git 2.4x', 'Conventional Commits 1.0', 'SemVer 2.0'],
  reviewedAt: '2026-08-01',
  lessons: [
    outline(
      'git-dasar',
      'Git Dasar yang Wajib',
      12,
      'Perintah yang benar-benar dipakai setiap hari.',
      '`status`, `add`, `commit`, `branch`, `merge`',
      'Perintah yang bisa membuang pekerjaan, dan cara berhati-hati dengannya',
    ),
    outline(
      'strategi-branch',
      'Strategi Branch: trunk-based vs git flow',
      10,
      'Dua pendekatan dan kapan masing-masing masuk akal.',
      'Trunk-based dengan rilis sering',
      'Git flow dan biayanya untuk tim kecil',
    ),
    outline(
      'pesan-commit',
      'Pesan Commit yang Menjelaskan *Kenapa*',
      10,
      'Diff sudah menunjukkan apa; pesan mengisi sisanya.',
      'Satu commit satu perubahan logis',
      'Conventional Commits sebagai kesepakatan',
    ),
    outline(
      'pull-request',
      'Pull Request & Code Review',
      11,
      'Mata kedua sebelum perubahan masuk.',
      'Deskripsi PR yang membantu reviewer',
      'Ukuran PR dan hubungannya dengan kualitas review',
    ),
    outline(
      'semver-changelog',
      'Semantic Versioning & Changelog',
      9,
      'Menomori rilis supaya artinya jelas.',
      'Major, minor, patch dan janjinya',
      'Changelog yang ditulis untuk pembaca, bukan untuk mesin',
    ),
  ],
  quiz: [
    q(
      'dp2-q1',
      'Kenapa satu commit sebaiknya berisi satu perubahan logis?',
      [
        'Supaya riwayat terlihat rapi',
        'Supaya review lebih mudah dan revert bisa dilakukan tanpa ikut membatalkan perubahan lain',
        'Karena Git membatasi ukuran commit',
        'Supaya repositori lebih kecil',
      ],
      1,
      'Commit yang menggabungkan fitur dan perbaikan tak berhubungan membuat revert menjadi pilihan antara membiarkan bug atau membuang fitur.',
    ),
  ],
  practice: {
    id: 'deployment/git-alur-rilis',
    title: 'Praktik bab ini',
    items: [
      'Kerjakan satu fitur di branch terpisah dan buka pull request',
      'Tulis lima pesan commit yang menjelaskan alasan, bukan daftar file',
      'Beri tag versi pada satu rilis dan tulis changelognya',
    ],
  },
});

const deployFe = defineChapter({
  slug: 'deploy-frontend',
  number: 3,
  title: 'Deploy Frontend (Next.js)',
  summary: 'Membawa aplikasi Next.js ke internet, dan memastikan ia tetap cepat di sana.',
  objectives: [
    'Membaca output build dan mengenali rute yang membengkak',
    'Men-deploy ke platform terkelola maupun ke server sendiri',
    'Mengatur caching dan revalidasi di produksi',
  ],
  prerequisites: [{ category: 'frontend-intermediate', chapter: 'nextjs' }],
  stackVersions: ['Next.js 16.2', 'Vercel', 'Cloudflare Pages'],
  reviewedAt: '2026-08-01',
  lessons: [
    outline(
      'build-produksi',
      'Build Produksi & Analisis Bundle',
      11,
      'Membaca apa yang sebenarnya dikirim ke pengguna.',
      'Menafsirkan tabel output `next build`',
      'Menemukan dependency yang tidak sepadan dengan ukurannya',
    ),
    outline(
      'deploy-vercel',
      'Deploy ke Vercel',
      10,
      'Jalur paling langsung untuk aplikasi Next.js.',
      'Menghubungkan repositori dan mengatur environment',
      'Preview deployment per pull request',
    ),
    outline(
      'alternatif-hosting',
      'Alternatif: Netlify, Cloudflare Pages, self-host',
      12,
      'Pilihan lain beserta konsekuensinya.',
      'Mode `standalone` untuk server sendiri',
      'Fitur Next.js yang butuh dukungan platform',
    ),
    outline(
      'env-nextjs-produksi',
      'Environment Variable di Produksi',
      10,
      'Memisahkan yang publik dari yang rahasia.',
      'Nilai per environment di dashboard platform',
      'Memastikan tidak ada rahasia di bundle klien',
    ),
    outline(
      'domain-https-fe',
      'Custom Domain & HTTPS',
      9,
      'Menghubungkan domain sendiri.',
      'Pengaturan DNS dan sertifikat otomatis',
      'Redirect www dan apex',
    ),
    outline(
      'caching-cdn-produksi',
      'Caching, CDN & Revalidation di Produksi',
      12,
      'Cepat tanpa menyajikan data basi.',
      'Header cache dan perilaku CDN',
      'On-demand revalidation setelah data berubah',
    ),
  ],
  quiz: [
    q(
      'dp3-q1',
      'Apa yang perlu diperiksa pada output `next build`?',
      [
        'Hanya apakah build berhasil',
        'Ukuran First Load JS per rute, untuk menemukan halaman yang terlalu berat',
        'Jumlah file di folder',
        'Waktu build saja',
      ],
      1,
      'Rute dengan First Load JS jauh di atas yang lain biasanya menandakan sebuah library berat ikut terbawa ke klien. Itu titik awal optimasi yang paling produktif.',
    ),
  ],
  practice: {
    id: 'deployment/deploy-frontend',
    title: 'Praktik bab ini',
    items: [
      'Jalankan `next build` dan catat tiga rute dengan bundle terbesar',
      'Deploy satu aplikasi ke platform pilihanmu dengan domain sendiri',
      'Verifikasi bahwa tidak ada rahasia yang muncul di bundle klien',
    ],
  },
});

const deployBe = defineChapter({
  slug: 'deploy-backend',
  number: 4,
  title: 'Deploy Backend',
  summary: 'Menjalankan Express dan Laravel di server sungguhan, beserta database dan migrasinya.',
  objectives: [
    'Men-deploy API ke VPS maupun ke PaaS',
    'Menjalankan migrasi tanpa menutup jalan rollback',
    'Memisahkan penyimpanan berkas dari server aplikasi',
  ],
  prerequisites: [{ category: 'backend-intermediate', chapter: 'express-intermediate' }],
  stackVersions: ['PM2 5', 'Nginx 1.27', 'PHP-FPM 8.3'],
  reviewedAt: '2026-08-01',
  lessons: [
    outline(
      'deploy-express',
      'Deploy Express: VPS vs PaaS',
      12,
      'Dua jalur dengan trade-off yang berbeda.',
      'VPS dengan PM2 dan Nginx',
      'PaaS: lebih cepat, lebih mahal, lebih sedikit kendali',
    ),
    outline(
      'deploy-laravel',
      'Deploy Laravel',
      12,
      'Menjalankan aplikasi PHP di produksi.',
      'Nginx + PHP-FPM, permission folder, dan cache konfigurasi',
      'Menjalankan queue worker sebagai proses terpisah',
    ),
    outline(
      'database-terkelola',
      'Database Terkelola',
      10,
      'Menyerahkan operasional database ke penyedia.',
      'Backup, replika, dan koneksi terenkripsi',
      'Connection pooling dan batas koneksi',
    ),
    outline(
      'migrasi-saat-deploy',
      'Menjalankan Migrasi saat Deploy',
      12,
      'Urutan yang menjaga rollback tetap mungkin.',
      'Expand → migrate → contract',
      'Kenapa migrasi destruktif bersama kodenya menutup jalan mundur',
    ),
    outline(
      'storage-cdn',
      'Penyimpanan Berkas & CDN',
      10,
      'Berkas unggahan tidak boleh tinggal di server aplikasi.',
      'Object storage dan URL bertanda tangan',
      'Menyajikan berkas lewat CDN dengan header yang benar',
    ),
  ],
  quiz: [
    q(
      'dp4-q1',
      'Kenapa migrasi destruktif tidak boleh dikirim bersama kode yang membutuhkannya?',
      [
        'Karena akan gagal',
        'Karena kalau kode perlu di-rollback, kolom yang sudah dihapus tidak bisa dikembalikan begitu saja',
        'Karena migrasi harus manual',
        'Karena melanggar SemVer',
      ],
      1,
      'Pola expand–migrate–contract: kirim perubahan aditif dulu, backfill, pindahkan kode, baru hapus bentuk lama di rilis berikutnya. Selalu ada jendela aman untuk mundur.',
    ),
  ],
  practice: {
    id: 'deployment/deploy-backend',
    title: 'Praktik bab ini',
    items: [
      'Deploy satu API ke VPS dengan reverse proxy dan proses yang dipantau',
      'Jalankan migrasi dengan pola expand–migrate–contract',
      'Pindahkan penyimpanan berkas ke object storage',
    ],
  },
});

const docker = defineChapter({
  slug: 'docker-container',
  number: 5,
  title: 'Docker & Container',
  summary: 'Mengemas aplikasi beserta lingkungannya supaya berjalan sama di mana pun.',
  objectives: [
    'Menulis Dockerfile multi-stage untuk Node dan PHP',
    'Menyusun lingkungan pengembangan lokal dengan Compose',
    'Menjaga image tetap kecil dan tidak membawa rahasia',
  ],
  prerequisites: [{ category: 'deployment', chapter: 'fondasi-deployment' }],
  stackVersions: ['Docker 27', 'Docker Compose v2'],
  reviewedAt: '2026-08-01',
  lessons: [
    outline(
      'kenapa-container',
      'Kenapa Container',
      9,
      'Masalah yang diselesaikan, dan yang tidak.',
      'Perbedaan container dan virtual machine',
      'Kapan container justru menambah kerumitan tanpa manfaat',
    ),
    outline(
      'dockerfile',
      'Dockerfile untuk Node & PHP',
      13,
      'Membangun image yang ramping.',
      'Multi-stage build dan pemisahan dependency build',
      'Urutan layer yang membuat cache bekerja',
    ),
    outline(
      'dockerignore',
      '`.dockerignore` & Ukuran Image',
      10,
      'Yang tidak ikut masuk sama pentingnya dengan yang masuk.',
      'Mengecualikan `node_modules`, `.git`, dan berkas rahasia',
      'Base image yang lebih kecil',
    ),
    outline(
      'compose',
      'Docker Compose untuk Pengembangan Lokal',
      12,
      'Satu perintah untuk seluruh tumpukan.',
      'Service app, database, dan redis',
      'Volume, jaringan, dan urutan startup',
    ),
    outline(
      'produksi-healthcheck',
      'Menjalankan di Produksi & Healthcheck',
      11,
      'Container yang bisa dipantau dan dipulihkan.',
      'Healthcheck dan restart policy',
      'Log ke stdout, bukan ke berkas di dalam container',
    ),
  ],
  quiz: [
    q(
      'dp5-q1',
      'Kenapa rahasia tidak boleh dimasukkan lewat `COPY` atau `ARG` di Dockerfile?',
      [
        'Karena melanggar sintaks',
        'Karena nilainya tersimpan di layer image dan bisa dibaca siapa pun yang memiliki image tersebut',
        'Karena membuat build lambat',
        'Karena Docker tidak mendukung string panjang',
      ],
      1,
      'Menghapus berkas rahasia di layer berikutnya tidak menghapusnya dari riwayat layer. Suntikkan rahasia saat runtime, atau pakai mekanisme secret khusus.',
    ),
  ],
  practice: {
    id: 'deployment/docker-container',
    title: 'Praktik bab ini',
    items: [
      'Tulis Dockerfile multi-stage untuk satu aplikasi Node',
      'Susun Compose berisi app + database + redis',
      'Kecilkan image sampai di bawah setengah ukuran awalnya',
    ],
  },
});

const cicd = defineChapter({
  slug: 'ci-cd',
  number: 6,
  title: 'CI/CD',
  summary:
    'Otomatisasi yang menjalankan pemeriksaan dan rilis, supaya tidak bergantung pada ingatan.',
  objectives: [
    'Menyusun pipeline lint → type-check → test → build',
    'Mengatur deploy otomatis beserta preview',
    'Menyiapkan rencana rollback sebelum dibutuhkan',
  ],
  prerequisites: [{ category: 'deployment', chapter: 'git-alur-rilis' }],
  stackVersions: ['GitHub Actions'],
  reviewedAt: '2026-08-01',
  lessons: [
    outline(
      'konsep-ci-cd',
      'Konsep CI vs CD',
      9,
      'Dua hal berbeda yang sering disebut sebagai satu.',
      'Continuous integration, delivery, dan deployment',
      'Apa yang benar-benar dibutuhkan project kecil',
    ),
    outline(
      'github-actions',
      'GitHub Actions: workflow, job, step',
      11,
      'Anatomi sebuah pipeline.',
      'Trigger, job, step, dan runner',
      'Cache dependency supaya pipeline tidak lambat',
    ),
    outline(
      'pipeline-pemeriksaan',
      'Pipeline: lint → type-check → test → build',
      12,
      'Urutan yang gagal secepat mungkin.',
      'Menjalankan pemeriksaan yang sama dengan yang di lokal',
      'Kenapa pipeline hijau adalah syarat, bukan bukti',
    ),
    outline(
      'deploy-otomatis',
      'Deploy Otomatis & Preview Deployment',
      11,
      'Dari merge ke produksi tanpa langkah manual.',
      'Deploy hanya setelah pemeriksaan lulus',
      'Preview per pull request untuk meninjau perubahan visual',
    ),
    outline(
      'secret-ci',
      'Secret di CI',
      10,
      'Kredensial yang dipakai pipeline.',
      'Menyimpan secret dan membatasi aksesnya',
      'Mencegah rahasia muncul di log build',
    ),
    outline(
      'rollback',
      'Rollback: direncanakan sebelum rilis',
      11,
      'Keputusan yang tidak boleh diimprovisasi saat sedang panik.',
      'Cara mengembalikan, berapa lama, dan apa yang tidak bisa dikembalikan',
      'Ambang batas yang memicu rollback, ditentukan di muka',
    ),
  ],
  quiz: [
    q(
      'dp6-q1',
      'Kenapa rencana rollback harus dibuat sebelum deploy, bukan saat terjadi masalah?',
      [
        'Supaya pipeline lebih cepat',
        'Karena saat produksi bermasalah tidak ada waktu untuk memikirkan langkah, dan sebagian hal memang tidak bisa dikembalikan',
        'Karena CI mewajibkannya',
        'Karena rollback selalu otomatis',
      ],
      1,
      'Beberapa hal tidak bisa dibatalkan: migrasi destruktif, email terkirim, pembayaran diproses, webhook dikirim. Itu harus diketahui sebelum tombol deploy ditekan.',
    ),
  ],
  practice: {
    id: 'deployment/ci-cd',
    title: 'Praktik bab ini',
    items: [
      'Susun workflow yang menjalankan lint, type-check, test, dan build',
      'Aktifkan deploy otomatis hanya bila seluruh pemeriksaan lulus',
      'Tulis rencana rollback satu halaman untuk aplikasimu',
    ],
  },
});

const setelahRilis = defineChapter({
  slug: 'setelah-rilis',
  number: 7,
  title: 'Setelah Rilis (Operasional)',
  summary: 'Pipeline hijau bukan akhir. Bab penutup: memantau, menelusuri, dan memulihkan.',
  objectives: [
    'Mengetahui aplikasi bermasalah sebelum pengguna melaporkannya',
    'Menelusuri satu permintaan dari log sampai penyebabnya',
    'Menguji pemulihan backup, bukan sekadar membuatnya',
  ],
  prerequisites: [{ category: 'deployment', chapter: 'ci-cd' }],
  stackVersions: ['Sentry', 'Core Web Vitals'],
  reviewedAt: '2026-08-01',
  lessons: [
    outline(
      'monitoring-uptime',
      'Monitoring & Uptime Check',
      10,
      'Tahu lebih dulu, bukan dari keluhan pengguna.',
      'Health check dari luar dan alert yang benar-benar dibaca',
      'Membedakan alert yang berarti dari kebisingan',
    ),
    outline(
      'error-tracking',
      'Error Tracking',
      11,
      'Mengumpulkan kegagalan yang benar-benar terjadi di produksi.',
      'Memasang Sentry dan mengelompokkan error',
      'Menyaring data pribadi sebelum dikirim',
    ),
    outline(
      'logging-terpusat',
      'Logging Terpusat & Correlation ID',
      11,
      'Menelusuri satu permintaan lintas layanan.',
      'Log terstruktur dan id yang mengalir ke semua baris',
      'Kenapa log di disk instance hilang saat instance diganti',
    ),
    outline(
      'analytics-web-vitals',
      'Analytics & Core Web Vitals di Produksi',
      11,
      'Mengukur pengalaman nyata, bukan hasil lab.',
      'LCP, INP, CLS dari pengguna sungguhan',
      'Menghormati privasi saat mengumpulkan data',
    ),
    outline(
      'backup-restore',
      'Backup & Restore Database',
      12,
      'Backup yang belum pernah diuji bukan backup.',
      'Jadwal, retensi, dan penyimpanan terpisah',
      'Latihan pemulihan secara berkala',
    ),
    outline(
      'checklist-deploy',
      'Checklist Pra-Deploy & Pasca-Deploy',
      11,
      'Daftar yang benar-benar dijalankan, bukan diasumsikan.',
      'Pemeriksaan sebelum rilis dengan bukti perintah',
      'Verifikasi setelah rilis: error rate, latensi, dan perilaku yang berubah',
    ),
  ],
  quiz: [
    q(
      'dp7-q1',
      'Kapan sebuah backup bisa disebut dapat diandalkan?',
      [
        'Saat berjalan otomatis setiap hari',
        'Saat proses pemulihannya sudah pernah diuji sampai berhasil',
        'Saat ukurannya besar',
        'Saat disimpan di server yang sama',
      ],
      1,
      'Backup yang tidak pernah dipulihkan adalah asumsi. Backup yang rusak, tidak lengkap, atau tidak bisa dibaca baru ketahuan pada saat paling buruk.',
    ),
    q(
      'dp7-q2',
      'Kenapa deploy belum selesai saat pipeline berwarna hijau?',
      [
        'Karena pipeline sering salah',
        'Karena perilaku di produksi harus diverifikasi: health check, error rate, latensi, dan fitur yang baru diubah',
        'Karena harus menunggu 24 jam',
        'Karena CI tidak menjalankan test',
      ],
      1,
      'Pipeline membuktikan kode lolos pemeriksaan, bukan bahwa aplikasi berjalan benar dengan data dan konfigurasi produksi. Verifikasi pasca-deploy adalah bagian dari deploy.',
    ),
  ],
  practice: {
    id: 'deployment/setelah-rilis',
    title: 'Praktik bab ini',
    items: [
      'Pasang error tracking dan picu satu error uji',
      'Tambahkan correlation id yang muncul di semua log satu permintaan',
      'Pulihkan satu backup ke database kosong dan buktikan datanya utuh',
      'Susun checklist pra-deploy dan pasca-deploy untuk aplikasimu',
    ],
  },
});

export const deployment = defineCategory({
  slug: 'deployment',
  order: 5,
  title: 'Deployment',
  tagline: 'Dari laptop ke internet',
  description:
    'Bab penutup kurikulum. Kode yang tidak pernah dipakai orang lain belum selesai — di sini kamu membawanya keluar, mengotomatiskan rilisnya, dan menjaganya tetap hidup setelah itu.',
  chapters: [fondasi, git, deployFe, deployBe, docker, cicd, setelahRilis],
});
